### ISSUE TITLE
Occasional errors when disconnecting: com.apple.CallKit.error.requesttransaction error 4

### ISSUE THREAD

**Issue by mikeknapp** [twilio/voice-callkit-quickstart-swift#6]
Thanks for providing this guide. Generally, everything generally works well - except that about 1 out of every 2, 3 or 4 calls, if the receiver of those calls initiates the disconnects, the following error is generated and the call doesn't actually disconnect properly:

`EndCallAction transaction request failed: The operation couldn’t be completed. (com.apple.CallKit.error.requesttransaction error 4.)`

The user then has to exit the application to find the call screen and end it that way. If they click on the green bar at the top of the screen (the "go back to the call" bar), they go back to my app, but there is no longer any way to disconnect.

The error means - I think - that the UUID can't be found. However, if I log the UUIDs, they all check out. It's very frustrating and confusing. I've even tried making deep copies of the UUIDs (`UUID(uuidString: action.callUUID.uuidString)`) at various points.

There's a race condition somewhere in your code, however, I'm not able to find it. 

This bug creates a really poor user experience that will be very jarring. You might not realise the disconnect didn't work for some period time -- at which point you might worry about what the other party heard!

**Comment by mikeknapp** [comment]
For you to be able to reproduce this, you'll need to have push notifications set up, and your server will need to be able to take an incoming call from party A (Xcode simulator) and then dial party B's client (your phone).

Party B should answer, and after a 5 - 10 seconds, hang up. The call will feel like it has disengaged - for both parties, however party B will still be connected.

However, it happens randomly. Sometimes it works fine - for 5 or 6 calls in a row sometimes, and then then next call, it happens.

**Comment by bchen-twilio** [comment]
Hi @mikeknapp 

Bobie here from the Voice SDK team and I am sorry that this bug is causing you trouble and giving you bad experience.
We've recently fixed a bug, right after beta6, that the UUIDs of the call-invite and the accepted and connected incoming call are inconsistent and that will cause CallKit trouble. Currently I'd suggest you to keep the UUID of the incoming call-invite and use the same UUID when trying to end the incoming TVOCall object.

Sorry for your inconvenience and we will do our best to get the next release out ASAP.

best,
-bobie

**Comment by mikeknapp** [comment]
Thanks @bchen-twilio!

How do I get the accurate call invite UUID though?

`callInviteReceived` in the `TVONotificationDelegate` is a `TVOCallInvite` object already. The UUID in that object seems to stay consistent for me, even when the bug occurs.

(One curious thing, in the  PushKit data for an incoming call there is this:`"twi_message_type": twilio.voice.cancel`. Does this sound right? That seems like a strange name...)

When will the new code be released? This is a really poor user experience to offer my users. It looks like something failed on 50% of the calls....

**Comment by bchen-twilio** [comment]
Hi @mikeknapp 

When the call-invite is received, you would [report the incoming call to the CallKit framework](https://github.com/twilio/voice-callkit-quickstart-swift/blob/master/SwiftVoiceCallKitQuickstart/ViewController.swift#L153) with the UUID from the `TVOCallInvite` object. To properly end this incoming call, [the quickstart uses the UUID of the `TVOCall` object from the `callDidDisconnect:` callback](https://github.com/twilio/voice-callkit-quickstart-swift/blob/master/SwiftVoiceCallKitQuickstart/ViewController.swift#L202), which can't be more reasonable. The problem is these two UUIDs are different and causing CallKit to throw the `requesttransaction error 4`.

A temporary workaround is to use the same UUID (from the `TVOCallInvite` object) to end the same incoming call.

Great question about the cancellation message - it's completely safe to be ignored. Twilio allows multiple mobile clients to be registered with the same identity and all of them will get the incoming call notification. Once the call is accepted by one of the clients, Twilio service will send the cancellation notification to all the clients with the same identity, as well as the client who received the call. The SDK intelligently ignores that cancellation notification since it knows this call is actually accepted by the local client.

-bobie

**Comment by mikeknapp** [comment]
Hi @bchen-twilio 

Thanks for the info! I still can't this to work. I can see that `callInvite.uuid` is a different UUID, however, even if I pass this to `performEndCallAction`, I still get the error. In fact, I even re-wrote the performEndCallAction to retry using the alternative UUID if there was a failure with the first one.... still no 🎲 .

When's the next release scheduled? This is driving me absolutely crazy!!! :-)

**Comment by bchen-twilio** [comment]
Hi @mikeknapp 

There is a line in the `provider:performAnswerCallAction:` method ([ViewController.swift#L332](https://github.com/twilio/voice-callkit-quickstart-swift/blob/master/SwiftVoiceCallKitQuickstart/ViewController.swift#L332)) where it updates the UUID of the TVOCall object to use theoretically the same UUID. Later when the `callDidDisconnect:` callback is triggered, it will pass the same UUID that we used to report the incoming call to the CallKit system.
Yes, all we want is to make sure the UUID used for reporting and ending the incoming call should be identical.

Please give it a try and let us know. It would also be great if you could provide us the verbose SDK log, as well as the UUIDs that you pass to the CallKit system, so that we could investigate base on it.

Also interested in the versions:
- iOS (and which device)
- Xcode
- TwilioVoiceClient (beta6, right?)

Thanks,
-bobie

**Comment by bchen-twilio** [comment]
Hi @mikeknapp 

We've just released the latest beta7. Could you give it a try and let us know if it fixed the issue your experiencing?
Thanks!

SDK: https://media.twiliocdn.com/sdk/ios/voice/releases/2.0.0-beta7/twilio-voice-ios-2.0.0-beta7.tar.bz2
Changelog: https://www.twilio.com/docs/api/voice-sdk/ios/changelog

-bobie

**Comment by mikeknapp** [comment]
Hi @bchen-twilio 

Thanks for letting me know. Unfortunately it's still happening to me. The code is pretty much exactly the same as the quickstart guide. Does something need to change in the quickstart guide to make this work?

Mike

**Comment by bchen-twilio** [comment]
@mikeknapp I am sorry to hear that you are still seeing the same problem.
I've created an internal bug ticket for tracking this.
Please bear with me and stay tuned for updates.

-bobie

**Comment by bchen-twilio** [comment]
Hi @mikeknapp 

I was able to reproduce the failed-to-end-call error #4 issue with the following steps:
- launch the app and register for incoming call push
- enable CallKit integration
- use another client to make call to this mobile client
- accept the incoming call on the mobile client
- after the call is connected, use the iPhone lock button to end the call
then it ended up with the error in the completion callback when sending the `CXEndCallAction` to the `CXCallController`.

I've checked the UUIDs of the TVOCallInvite and the TVOCall objects and they are all the same.
Another clue is that if I tried to disconnect the call via the API button, which calls `TVOCall.disconnect` directly and it never got into this error.

Let me try to investigate what's different between these two flows and let you know if I have any update. I have a feeling the CallKit framework has something to do with this issue.

-bobie

**Comment by mikeknapp** [comment]
Thanks @bchen-twilio! Just fyi, I've moved off this api (unrelated reason; mainly cost), and I'm using your video API now. I was actually having a similar issue with the sample code -- so I spent a day rewriting it using the structure in Apple's "Speakerbox" sample app. That seems to work better -- plus the code is a lot easier to understand. It might be worth checking that out! :) Thanks for your help.

**Comment by bchen-twilio** [comment]
@mikeknapp 

Oh I hate to see you move away from the Voice SDK :(
Actually our CallKit quickstart samples are written based on the Speakerbox sample app, though probably a very early version of it. Anyway we'll definitely check out the latest Speakerbox sample and update ours.

I am going to close this issue but please feel free to re-open or reach out to us any time in the future. Thanks again!

**Comment by geoffliddiard** [comment]
Hi @bchen-twilio,

I'm experiencing this issue. I can reproduce it consistently by hanging up an incoming call that was answered on the lock screen using the native CallKit UI. Did you find a work around for this?

Thanks

**Comment by bchen-twilio** [comment]
Hi @geoffliddiard 

We actually have a test case to answer the call on the lock screen and hang up. Steps:
- background the app (optional) and lock the phone
- make a call from another client
- answer the incoming (CallKit) call on the lock screen
- hang up after the call is connected for a few seconds

Do I miss any steps or do something differently?

Let me know :)
Thanks
-bobie

**Comment by lottadot** [comment]
I believe I've been seeing something similar. If I do those exact same steps, the calling-end eventually receives a `TVOCallDelegate:callDidDisconnect` and as such wraps up the disconnected call OK.

What seems to be more reproducible is:
* Apps is running on both devices.
* Answer on receiving app.
* Wait for your UI to show for the call.
* 1-3 seconds cancel the call on the receiving app.

The calling app will sometimes receive the `TVOCallDelegate:callDidDisconnect` and finish properly. Other times, it will receive `CXProvider:didDeactivateAudioSession` but *never* receive the `TVOCallDelegate:callDidDisconnect`.

I’m using iOS 10.3.x devices, Xcode 8.3.2 w/ Twilio Voice SDK 2.0 #9.

**Comment by bchen-twilio** [comment]
Hey @lottadot 

Interesting. By `1-3 seconds cancel the call on the receiving app` did you mean that the receiver client called `TVOCallInvite.reject` upon the incoming call?
The caller should definitely get a did-disconnect callback whether the call is rejected or timed out.

Just to make sure, the two client apps are registered with different identities in their access tokens, right?

Anyway I'll try to reproduce with the steps you provide.
Thanks!

**Comment by lottadot** [comment]
Hi @bchen-twilio , no, it would be the equivalent of the user actively choosing to end the call within the application. i.e. https://github.com/twilio/voice-callkit-quickstart-swift/blob/master/SwiftVoiceCallKitQuickstart/ViewController.swift#L83

Yes, each user (logged into our app, on each device) is unique, therefore has a Twilio Token that's derived by their unique UserId.

I might be able to give you a call SID of a call that I'd seen this happen on. Let me know if that would help.

**Comment by bchen-twilio** [comment]
So basically the receiver calls `TVOCall.disconnect` but the caller is not getting did-disconnect callback occasionally?
Not sure if call-SIDs would help at the moment but SDK logs on both sides could probably give us some insights to make sure what are/aren't correctly triggered on the signaling perspective.

**Comment by lottadot** [comment]
Yes, I believe that's the case. I can try and repeat it with logging verbosity .verbose logs; but I won't be able to make that happen until Monday. If you think it warrants a different ticket (I don't want to hijack this one if this is a different issue) let me know.

**Comment by bchen-twilio** [comment]
Thanks @lottadot.
Actually we do appreciate if you could open a new ticket under the regular Swift quickstart since we've merged the CallKit one into just one to make our life easier.

Happy Friday and enjoy your weekend!
-bobie
